/**
 * Ingredient helpers — build the payload objects that the Vibes generation
 * endpoints expect for applying (or inline-creating) characters, styles,
 * and scenes.
 *
 * Ported 1:1 from vibes_api/ingredients.py.
 *
 * Three ingredient types in Vibes:
 *   - CHARACTER  (UI: "Character")  → attaches via `orefImageHandle`
 *   - STYLE      (UI: "Style")      → attaches via `srefImageHandle`
 *   - SETTING    (UI: "Scene")      → attaches via `settingImageHandles`
 *
 * For each, there are three ways to reference the ingredient in a generation:
 *   1. By existing ingredient ID (use `IngredientRef.byId()`).
 *      → goes in the `ingredients` array on the request body.
 *   2. By image entity ID of an uploaded image (use `CreateIngredient.byImageEntId()`).
 *      → goes in the `createIngredients` array.
 *   3. By name only (use `CreateIngredient.byName()`).
 *      → also goes in `createIngredients`.
 */

import { coerce, IngredientType } from "./models";

/** Reference an EXISTING ingredient by its ingredientId. */
export const IngredientRef = {
  /** Reference an existing ingredient by its ID.
   *
   * @param ingredientId  The `ingredientId` from `listIngredients()`.
   * @param ingredientType  CHARACTER, STYLE, or SETTING.
   * @param name  Display name (matches the ingredient's name in the library).
   * @param imageUrl  URL of the ingredient's image (used as a thumbnail).
   */
  byId(opts: {
    ingredientId: string;
    ingredientType: IngredientType | string;
    name: string;
    imageUrl: string;
  }): Record<string, unknown> {
    return {
      ingredientId: opts.ingredientId,
      ingredientType: coerce(opts.ingredientType as string),
      name: opts.name,
      imageUrl: opts.imageUrl,
    };
  },
};

/** Builder for an INLINE ingredient creation (no pre-existing ingredient). */
export const CreateIngredient = {
  /** Create a new ingredient from an uploaded image.
   *
   * @param imageEntId  The `imageEntId` from `uploadImage()` or `uploadImageFile()`.
   * @param ingredientType  CHARACTER, STYLE, or SETTING.
   * @param name  Display name for the new ingredient.
   * @param imageUrl  URL of the uploaded image.
   */
  byImageEntId(opts: {
    imageEntId: string;
    ingredientType: IngredientType | string;
    name: string;
    imageUrl: string;
  }): Record<string, unknown> {
    return {
      sourceImageEntId: opts.imageEntId,
      ingredientType: coerce(opts.ingredientType as string),
      name: opts.name,
      imageUrl: opts.imageUrl,
    };
  },

  /** Create a new ingredient by name only.
   *
   * The server will use the image generated by the prompt as the
   * ingredient image.
   */
  byName(opts: {
    ingredientType: IngredientType | string;
    name: string;
  }): Record<string, unknown> {
    return {
      ingredientType: coerce(opts.ingredientType as string),
      name: opts.name,
    };
  },
};

/** Convenience builder: combine character/style/scene refs into a payload.
 *
 * Pass either `ingredients=[...]` and `createIngredients=[...]`
 * (already-built payload dicts), or the convenience parameters
 * `character=...`, `style=...`, `scene=...` (each can be either
 * an `IngredientRef` or `CreateIngredient` dict — this function
 * will route it to the correct array based on its keys).
 *
 * @returns `{ ingredients?: [...], createIngredients?: [...] }`
 */
export function buildIngredientPayload(opts: {
  ingredients?: Record<string, unknown>[];
  createIngredients?: Record<string, unknown>[];
  character?: Record<string, unknown>;
  style?: Record<string, unknown>;
  scene?: Record<string, unknown>;
}): Record<string, unknown> {
  const finalIngredients = [...(opts.ingredients ?? [])];
  const finalCreate = [...(opts.createIngredients ?? [])];

  for (const ing of [opts.character, opts.style, opts.scene]) {
    if (!ing) continue;
    if ("ingredientId" in ing) {
      finalIngredients.push(ing);
    } else {
      finalCreate.push(ing);
    }
  }

  const payload: Record<string, unknown> = {};
  if (finalIngredients.length > 0) payload.ingredients = finalIngredients;
  if (finalCreate.length > 0) payload.createIngredients = finalCreate;
  return payload;
}
